controller_manager:
  ros__parameters:
    update_rate: 20

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - joint-1
      - joint-2
      - joint-3
      - joint-4
      - joint-5
      - joint-6
      - joint_right-finger
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    state_publish_rate: 20.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
